version: '3'

services:

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Nodar126
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'

  web:
    build: .
    tty: true
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    ports:
      - '8001:8000'
    depends_on:
      - db
      - redis

  celery:
    build: .
    tty: true
    command: celery -A config worker -l INFO
    depends_on:
      - redis
      - web

  celery-beat:
    build: .
    tty: true
    command: celery -A config beat -l INFO -S django
    depends_on:
      - redis
      - web

volumes:
  pg_data:
