version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Nodar126
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    command: docker-compose exec db psql -U postgres && create database habit_database; && \q && docker-compose exec db psql -U habit_database

  web:
    build: .
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    ports:
      - '8001:8000'

volumes:
  pg_data:
