version: '3'

services:

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  db:
    image: postgres
    environment:
      - POSTGRES_DB=habit_database
      - POSTGRES_PASSWORD=Nodar126
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'

  web:
    build: .
    tty: true
    command: bash -c 'sleep 10 && python manage.py migrate && python manage.py runserver 0.0.0.0:8001'
    ports:
      - '8000:8001'
    depends_on:
      - db
      - redis

  celery:
    build: .
    tty: true
    command: celery -A config worker -l INFO
    depends_on:
      - web

  celery-beat:
    build: .
    tty: true
    command: celery -A config beat --logfile TEXT
    depends_on:
      - celery

volumes:
  pg_data:
